import React, { useEffect, useState, useMemo } from 'react';
import useGroupStore from '../store/useGroupStore';
import { 
  BarChart3, 
  Users, 
  PieChart, 
  FileText, 
  ChevronRight, 
  ArrowLeft, 
  Printer, 
  Download, 
  Calendar,
  Clock,
  TrendingUp,
  Wallet,
  ArrowUpRight,
  ArrowDownLeft,
  HandCoins,
  Receipt
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { useParams, useNavigate } from 'react-router-dom';

const Reports = () => {
  const { groups, fetchGroups, activeGroup, fetchGroupDetails, loading } = useGroupStore();
  const [selectedGroupId, setSelectedGroupId] = useState(null);
  const [reportDate, setReportDate] = useState(new Date());

  useEffect(() => {
    fetchGroups();
  }, []);

  const handleGroupClick = async (groupId) => {
    setSelectedGroupId(groupId);
    setReportDate(new Date());
    await fetchGroupDetails(groupId);
  };

  const totalGroups = groups.length;
  const totalMembers = groups.reduce((sum, group) => sum + (group.members?.length || 0), 0);
  const averageMembers = groups.length ? (totalMembers / groups.length).toFixed(1) : '0.0';

  if (selectedGroupId && activeGroup && activeGroup._id === selectedGroupId) {
    const { summary, expenses, settlements, members } = activeGroup;

    return (
      <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
        <div className="flex items-center justify-between">
          <button 
            onClick={() => setSelectedGroupId(null)}
            className="flex items-center gap-2 text-slate-500 hover:text-primary-600 font-bold transition-colors"
          >
            <ArrowLeft size={20} /> Back to Reports
          </button>
          <div className="flex items-center gap-2">
            <button 
              onClick={() => window.print()}
              className="p-3 bg-white dark:bg-slate-900 border rounded-2xl text-slate-600 hover:text-primary-600 shadow-sm transition-all"
              title="Print Report"
            >
              <Printer size={20} />
            </button>
            <div className="px-4 py-2 bg-primary-50 dark:bg-primary-900/20 text-primary-600 dark:text-primary-400 rounded-xl text-xs font-bold border border-primary-100 dark:border-primary-900/30 flex items-center gap-2">
              <Clock size={14} /> 
              Last Updated: {reportDate.toLocaleString()}
            </div>
          </div>
        </div>

        {/* Report Content - Screenshot Friendly */}
        <div id="report-content" className="bg-white dark:bg-slate-900 rounded-[2.5rem] border shadow-2xl overflow-hidden p-8 md:p-12 space-y-12">
          {/* Header */}
          <div className="flex flex-col md:flex-row justify-between items-start gap-6 border-b pb-12">
            <div>
              <div className="flex items-center gap-3 mb-2">
                <div className="p-3 bg-primary-600 text-white rounded-2xl shadow-lg shadow-primary-500/20">
                  <FileText size={28} />
                </div>
                <h1 className="text-4xl font-black tracking-tight">{activeGroup.name}</h1>
              </div>
              <p className="text-slate-500 text-lg">{activeGroup.description || 'Comprehensive financial report and expense breakdown.'}</p>
            </div>
            <div className="text-right">
              <p className="text-[10px] uppercase font-black tracking-widest text-slate-400 mb-1">Generated By</p>
              <p className="font-bold text-xl text-primary-600">SmartSplit Report Engine</p>
              <p className="text-slate-500 text-sm mt-1">{reportDate.toDateString()}</p>
            </div>
          </div>

          {/* Key Metrics */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            <div className="p-6 bg-slate-50 dark:bg-slate-950 rounded-3xl border text-center">
              <p className="text-xs font-black uppercase tracking-wider text-slate-400 mb-2">Total Expenses</p>
              <p className="text-3xl font-black text-slate-900 dark:text-white">₹{summary?.totalExpense?.toFixed(2) || '0.00'}</p>
            </div>
            <div className="p-6 bg-slate-50 dark:bg-slate-950 rounded-3xl border text-center">
              <p className="text-xs font-black uppercase tracking-wider text-slate-400 mb-2">Total Members</p>
              <p className="text-3xl font-black text-slate-900 dark:text-white">{members?.length || 0}</p>
            </div>
            <div className="p-6 bg-slate-50 dark:bg-slate-950 rounded-3xl border text-center">
              <p className="text-xs font-black uppercase tracking-wider text-slate-400 mb-2">Settled Amount</p>
              <p className="text-3xl font-black text-emerald-600">₹{settlements?.filter(s => s.status === 'completed').reduce((sum, s) => sum + s.amount, 0).toFixed(2) || '0.00'}</p>
            </div>
            <div className="p-6 bg-slate-50 dark:bg-slate-950 rounded-3xl border text-center">
              <p className="text-xs font-black uppercase tracking-wider text-slate-400 mb-2">Pending Dues</p>
              <p className="text-3xl font-black text-amber-600">₹{(summary?.totalExpense - settlements?.filter(s => s.status === 'completed').reduce((sum, s) => sum + s.amount, 0)).toFixed(2) || '0.00'}</p>
            </div>
          </div>

          {/* Member Breakdown */}
          <div>
            <h2 className="text-2xl font-black mb-6 flex items-center gap-3">
              <Users size={24} className="text-primary-600" /> Member Balances
            </h2>
            <div className="overflow-x-auto">
              <table className="w-full text-left">
                <thead>
                  <tr className="text-slate-400 text-xs uppercase tracking-widest border-b">
                    <th className="pb-4 font-black">Member</th>
                    <th className="pb-4 font-black text-center">Paid</th>
                    <th className="pb-4 font-black text-center">Share</th>
                    <th className="pb-4 font-black text-right">Balance</th>
                  </tr>
                </thead>
                <tbody className="divide-y">
                  {summary?.memberBalances?.map((record) => {
                    const member = members.find(m => m.user?._id?.toString() === (record.user?._id?.toString() || record.user?.toString()));
                    const balance = record.netBalance || 0;
                    return (
                      <tr key={record.user?._id || record.user} className="group hover:bg-slate-50 dark:hover:bg-slate-800/30 transition-colors">
                        <td className="py-5">
                          <div className="flex items-center gap-3">
                            <img src={member?.user?.avatar} className="w-10 h-10 rounded-xl shadow-sm border" />
                            <div>
                              <p className="font-bold">{member?.user?.name || 'Unknown'}</p>
                              <p className="text-xs text-slate-500">{member?.user?.email}</p>
                            </div>
                          </div>
                        </td>
                        <td className="py-5 text-center font-bold">₹{record.totalPaid?.toFixed(2)}</td>
                        <td className="py-5 text-center font-bold">₹{record.totalShare?.toFixed(2)}</td>
                        <td className="py-5 text-right">
                          <span className={`px-4 py-2 rounded-xl text-sm font-black ${
                            balance > 0 ? 'bg-emerald-50 text-emerald-600' : 
                            balance < 0 ? 'bg-rose-50 text-rose-600' : 'bg-slate-100 text-slate-500'
                          }`}>
                            {balance > 0 ? `+₹${balance.toFixed(2)}` : balance < 0 ? `-₹${Math.abs(balance).toFixed(2)}` : 'Settle'}
                          </span>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>

          <div className="grid md:grid-cols-2 gap-12 pt-8">
            {/* Recent Expenses */}
            <div>
              <h3 className="text-xl font-black mb-6 flex items-center gap-3">
                <Receipt size={20} className="text-primary-600" /> Recent Expenses
              </h3>
              <div className="space-y-4">
                {expenses?.slice(0, 5).map(expense => (
                  <div key={expense._id} className="p-4 bg-slate-50 dark:bg-slate-950 rounded-2xl border flex justify-between items-center">
                    <div>
                      <p className="font-bold truncate max-w-[150px]">{expense.description}</p>
                      <p className="text-[10px] text-slate-400">{new Date(expense.createdAt).toLocaleDateString()}</p>
                    </div>
                    <div className="text-right">
                      <p className="font-black">₹{expense.amount.toFixed(2)}</p>
                      <p className="text-[10px] text-primary-600 font-bold uppercase">{expense.category}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Recent Settlements */}
            <div>
              <h3 className="text-xl font-black mb-6 flex items-center gap-3">
                <HandCoins size={20} className="text-emerald-600" /> Recent Settlements
              </h3>
              <div className="space-y-4">
                {settlements?.filter(s => s.status === 'completed').slice(0, 5).map(settlement => (
                  <div key={settlement._id} className="p-4 bg-emerald-50/30 dark:bg-emerald-500/5 rounded-2xl border border-emerald-100 dark:border-emerald-500/20 flex justify-between items-center">
                    <div>
                      <p className="font-bold text-emerald-700 dark:text-emerald-400">₹{settlement.amount.toFixed(2)}</p>
                      <p className="text-[10px] text-slate-400">{new Date(settlement.createdAt).toLocaleDateString()}</p>
                    </div>
                    <div className="text-right text-xs">
                      <p className="font-medium text-slate-500">{settlement.payerId?.name}</p>
                      <p className="text-[10px] text-slate-400">to {settlement.receiverId?.name}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
          
          <div className="pt-12 border-t text-center">
            <p className="text-sm text-slate-400">© {new Date().getFullYear()} SmartSplit. All group calculations are final as of the timestamp above.</p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-4xl font-black tracking-tight">Financial Reports</h1>
        <p className="text-slate-500 text-lg">In-depth analysis and group performance metrics.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <motion.div whileHover={{ y: -5 }} className="bg-white dark:bg-slate-900 rounded-[2rem] p-8 border shadow-xl shadow-primary-500/5 transition-all">
          <div className="p-4 bg-primary-100 dark:bg-primary-900/20 text-primary-600 rounded-2xl w-fit mb-6">
            <FileText size={32} />
          </div>
          <p className="text-sm font-black uppercase tracking-widest text-slate-400 mb-1">Total Groups</p>
          <p className="text-5xl font-black">{totalGroups}</p>
        </motion.div>
        <motion.div whileHover={{ y: -5 }} className="bg-white dark:bg-slate-900 rounded-[2rem] p-8 border shadow-xl shadow-emerald-500/5 transition-all">
          <div className="p-4 bg-emerald-100 dark:bg-emerald-900/20 text-emerald-600 rounded-2xl w-fit mb-6">
            <Users size={32} />
          </div>
          <p className="text-sm font-black uppercase tracking-widest text-slate-400 mb-1">Total Network</p>
          <p className="text-5xl font-black">{totalMembers}</p>
        </motion.div>
        <motion.div whileHover={{ y: -5 }} className="bg-white dark:bg-slate-900 rounded-[2rem] p-8 border shadow-xl shadow-blue-500/5 transition-all">
          <div className="p-4 bg-blue-100 dark:bg-blue-900/20 text-blue-600 rounded-2xl w-fit mb-6">
            <TrendingUp size={32} />
          </div>
          <p className="text-sm font-black uppercase tracking-widest text-slate-400 mb-1">Avg. Connections</p>
          <p className="text-5xl font-black">{averageMembers}</p>
        </motion.div>
      </div>

      <div className="bg-white dark:bg-slate-900 rounded-[2.5rem] p-8 border shadow-sm">
        <h2 className="text-2xl font-black mb-8 flex items-center gap-3">
          <PieChart size={28} className="text-primary-600" /> Active Groups
        </h2>
        {loading && !selectedGroupId ? (
          <div className="text-center py-20 flex flex-col items-center gap-4">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600" />
            <p className="text-slate-500 font-bold">Aggregating data...</p>
          </div>
        ) : groups.length === 0 ? (
          <div className="text-center py-20 bg-slate-50 dark:bg-slate-800/50 rounded-3xl border border-dashed">
            <p className="text-slate-500">No groups found. Generate your first group to start reporting.</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {groups.map((group) => (
              <motion.div
                key={group._id}
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                onClick={() => handleGroupClick(group._id)}
                className="group p-6 rounded-3xl bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 hover:border-primary-500/50 hover:bg-white dark:hover:bg-slate-900 transition-all cursor-pointer relative overflow-hidden"
              >
                <div className="absolute top-0 right-0 p-4 opacity-0 group-hover:opacity-100 transition-opacity">
                  <ChevronRight size={20} className="text-primary-600" />
                </div>
                <div className="flex flex-col h-full justify-between">
                  <div>
                    <span className="px-3 py-1 bg-white dark:bg-slate-800 text-[10px] font-black uppercase tracking-widest rounded-lg border shadow-sm">{group.category}</span>
                    <h3 className="text-xl font-black mt-4 mb-2 truncate">{group.name}</h3>
                    <p className="text-slate-500 text-sm line-clamp-2 mb-4">{group.description}</p>
                  </div>
                  <div className="flex items-center justify-between pt-4 border-t border-slate-200 dark:border-slate-800">
                    <div className="flex items-center gap-2 text-slate-400">
                      <Users size={16} />
                      <span className="text-xs font-bold">{group.members.length} members</span>
                    </div>
                    <span className="text-primary-600 font-black text-sm">View Report</span>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default Reports;
